import { useEffect, useState, type CSSProperties } from 'react';
import { getSupabaseBrowserClient } from '../../lib/supabase';

const card: CSSProperties = { background:'#fff', border:'1px solid #eadfd2', borderRadius:14, padding:22, boxShadow:'0 6px 20px rgba(67,45,25,.05)' };
const input: CSSProperties = { width:'100%', padding:'10px 12px', border:'1px solid #d9cbbb', borderRadius:8, marginTop:6, boxSizing:'border-box' };
const db = getSupabaseBrowserClient();
// Authenticated studio routes are only mounted when the browser client is configured.
const supabase = db!;
function useOrgId(provided: string | null) { const [id,setId]=useState<string|null>(provided); useEffect(()=>{ if(provided || !db) return; void db.auth.getUser().then(async({data})=>{ if(!data.user)return; const {data: m}=await db.from('organization_members').select('organization_id').eq('user_id',data.user.id).limit(1).maybeSingle(); if(m?.organization_id)setId(m.organization_id); }); },[provided]); return id; }

export function TeamWorkspace({ organizationId }: { organizationId: string | null }) {
  organizationId = useOrgId(organizationId);
  const [members, setMembers] = useState<any[]>([]); const [invites, setInvites] = useState<any[]>([]); const [email, setEmail] = useState(''); const [role, setRole] = useState('designer'); const [message, setMessage] = useState('');
  const load = async () => { if (!organizationId) return; const [{ data: m }, { data: i }] = await Promise.all([supabase.from('organization_members').select('user_id,role,created_at').eq('organization_id', organizationId), supabase.from('organization_invitations').select('*').eq('organization_id', organizationId).order('created_at',{ascending:false})]); setMembers(m ?? []); setInvites(i ?? []); };
  useEffect(() => { void load(); }, [organizationId]);
  const invite = async () => { if (!organizationId || !email.trim()) return; const { error } = await supabase.from('organization_invitations').insert({ organization_id: organizationId, email: email.trim().toLowerCase(), role }); setMessage(error ? error.message : 'Invitation recorded. Send the secure invite from your identity provider.'); if (!error) { setEmail(''); void load(); } };
  return <div style={{maxWidth:1000,margin:'0 auto',padding:'28px 24px'}}><div style={{marginBottom:24}}><div style={{fontSize:12,color:'#9a7655',fontWeight:800,textTransform:'uppercase',letterSpacing:1}}>Studio administration</div><h1 style={{margin:'6px 0'}}>Team</h1><p style={{color:'#756555'}}>Keep designers, production, and client viewers aligned without exposing project data across studios.</p></div><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:18}}><section style={card}><h3>Invite a collaborator</h3><input aria-label="Email" placeholder="name@studio.com" value={email} onChange={e=>setEmail(e.target.value)}/><select aria-label="Role" style={input} value={role} onChange={e=>setRole(e.target.value)}><option value="designer">Designer</option><option value="production">Production</option><option value="viewer">Viewer</option><option value="admin">Admin</option></select><button style={{marginTop:12,padding:'10px 16px',border:0,borderRadius:8,background:'#4e3928',color:'#fff',fontWeight:700}} onClick={invite}>Create invite</button>{message&&<p style={{fontSize:12,color:'#756555'}}>{message}</p>}</section><section style={card}><h3>Members</h3>{members.length===0?<p style={{color:'#8a7762'}}>No members loaded for this studio.</p>:members.map(m=><div key={m.user_id} style={{display:'flex',justifyContent:'space-between',padding:'10px 0',borderBottom:'1px solid #f0e7dd'}}><span>{m.user_id.slice(0,8)}…</span><b style={{textTransform:'capitalize'}}>{m.role}</b></div>)}</section></div><section style={{...card,marginTop:18}}><h3>Pending invitations</h3>{invites.length===0?<p style={{color:'#8a7762'}}>No pending invitations.</p>:invites.map(i=><div key={i.id} style={{display:'flex',justifyContent:'space-between',padding:'10px 0'}}><span>{i.email}</span><span>{i.role} · {i.status}</span></div>)}</section></div>;
}

export function RulesWorkspace({ organizationId }: { organizationId: string | null }) {
  organizationId = useOrgId(organizationId);
  const [values,setValues]=useState({measurement_units:'mm',default_external_wall_mm:'254',default_internal_wall_mm:'152.4',default_ceiling_height_mm:'2700',standards:'{"toleranceMm": 0.5, "defaultPlinthMm": 100}'}); const [saved,setSaved]=useState('');
  useEffect(()=>{ if(organizationId) void supabase.from('organization_settings').select('*').eq('organization_id',organizationId).maybeSingle().then(({data})=>{if(data)setValues(v=>({...v, ...Object.fromEntries(Object.entries(data).map(([k,x])=>[k,String(x)]))}));}); },[organizationId]);
  const save=async()=>{if(!organizationId)return;let parsed={};try{parsed=JSON.parse(values.standards)}catch{setSaved('Standards must be valid JSON');return} const {error}=await supabase.from('organization_settings').upsert({organization_id:organizationId,measurement_units:values.measurement_units,default_external_wall_mm:Number(values.default_external_wall_mm),default_internal_wall_mm:Number(values.default_internal_wall_mm),default_ceiling_height_mm:Number(values.default_ceiling_height_mm),standards:parsed,updated_at:new Date().toISOString()});setSaved(error?.message??'Company rules saved and will be used by validation and production preflight.');};
  return <div style={{maxWidth:900,margin:'0 auto',padding:'28px 24px'}}><div style={{fontSize:12,color:'#9a7655',fontWeight:800,textTransform:'uppercase',letterSpacing:1}}>Studio standards</div><h1>Company Rules</h1><p style={{color:'#756555'}}>These are design guardrails—not generic AI prompts. They become defaults for measurement, module fit, and production checks.</p><section style={card}><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:16}}>{[['measurement_units','Units'],['default_external_wall_mm','External wall (mm)'],['default_internal_wall_mm','Internal partition (mm)'],['default_ceiling_height_mm','Default ceiling (mm)']].map(([key,label])=><label key={key}>{label}<input style={input} value={(values as any)[key]} onChange={e=>setValues(v=>({...v,[key]:e.target.value}))}/></label>)}</div><label style={{display:'block',marginTop:18}}>Structured standards JSON<textarea style={{...input,minHeight:110,fontFamily:'monospace'}} value={values.standards} onChange={e=>setValues(v=>({...v,standards:e.target.value}))}/></label><button onClick={save} style={{marginTop:14,padding:'10px 16px',border:0,borderRadius:8,background:'#4e3928',color:'#fff',fontWeight:700}}>Save rules</button>{saved&&<p style={{fontSize:12,color:'#756555'}}>{saved}</p>}</section></div>;
}

export function SettingsWorkspace({ organizationId, orgName }: { organizationId: string | null; orgName: string }) { organizationId = useOrgId(organizationId); return <div style={{maxWidth:900,margin:'0 auto',padding:'28px 24px'}}><div style={card}><div style={{fontSize:12,color:'#9a7655',fontWeight:800,textTransform:'uppercase',letterSpacing:1}}>Workspace settings</div><h1>{orgName || 'Your studio'}</h1><p style={{color:'#756555'}}>ULTIDA keeps your studio identity, units, rules, provider readiness, and account security in one place.</p><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:14}}><div><b>Organization</b><p>{organizationId ? 'Connected to canonical Supabase workspace' : 'Loading workspace…'}</p></div><div><b>Measurement authority</b><p>Millimetres are canonical; feet/inches are display-only.</p></div><div><b>AI providers</b><p>Unavailable providers are shown honestly; no fabricated results.</p></div><div><b>Security</b><p>Project data is protected by organization-level RLS.</p></div></div></div></div>; }
