import { Calculator, CircleAlert, FileText, LockKeyhole } from 'lucide-react';
import { Badge, Card, CardContent, CardHeader } from '../ui/primitives';

type Props = { briefSaved: boolean; planApproved: boolean; sceneVersionId: string | null; moduleCount: number };

export function CommercialWorkspace({ briefSaved, planApproved, sceneVersionId, moduleCount }: Props) {
  const ready = Boolean(briefSaved && planApproved && sceneVersionId && moduleCount);
  return <section className="commercial-workspace"><div className="workspace-heading"><div><small>COMMERCIAL / CONTROLLED ESTIMATE</small><h2>Price only what the approved scene can prove.</h2><p>Quotes inherit the brief, measured plan and scene version. Missing catalog prices stay visible instead of becoming invented totals.</p></div><Badge tone={ready ? 'success' : 'accent'}>{ready ? 'Ready for pricing' : 'Blocked'}</Badge></div><div className="commercial-layout"><Card><CardHeader><div><small>QUOTE WORKSPACE</small><h3>Estimate readiness</h3></div><Calculator size={20} /></CardHeader><CardContent><div className="commercial-check"><strong>Source context</strong><span className={briefSaved ? 'commercial-ready' : 'commercial-blocked'}>{briefSaved ? 'Brief saved' : 'Brief required'}</span></div><div className="commercial-check"><strong>Measured design</strong><span className={planApproved && sceneVersionId ? 'commercial-ready' : 'commercial-blocked'}>{planApproved && sceneVersionId ? 'Approved plan and scene linked' : 'Approved plan and scene required'}</span></div><div className="commercial-check"><strong>Priced modules</strong><span className="commercial-blocked">Catalog price book unavailable</span></div><div className="commercial-empty"><FileText size={28} /><h3>{ready ? 'Quote not issued' : 'Quote is blocked'}</h3><p>{ready ? `${moduleCount} scene modules are ready for catalog pricing, labour, GST and margin calculation.` : 'Complete the brief, approve the plan, create a scene and configure catalog prices before issuing a quote.'}</p></div></CardContent></Card><Card className="commercial-side"><CardHeader><div><small>NEXT ACTION</small><h3>Configure price book</h3></div><LockKeyhole size={20} /></CardHeader><CardContent><p>Commercial output is intentionally unavailable until catalog prices, labour rules, GST and margin controls are configured.</p><div className="commercial-note"><CircleAlert size={16} /><span>No quote has been generated.</span></div></CardContent></Card></div></section>;
}
