import { z } from 'zod';

export const RoomTypeSchema = z.enum(['kitchen', 'living', 'bedroom', 'bathroom', 'dining', 'study', 'pooja', 'utility', 'other']);
export const ModuleFamilySchema = z.enum(['kitchen-base', 'kitchen-wall', 'kitchen-tall', 'kitchen-corner', 'wardrobe', 'tv-unit', 'crockery', 'pooja', 'sofa', 'bed', 'study', 'utility', 'dining', 'false-ceiling', 'storage']);
export const MaterialSlotSchema = z.enum(['carcass', 'shutter', 'countertop', 'back-panel', 'hardware', 'fabric', 'metal', 'glass', 'lighting']);
export const ModuleElementKindSchema = z.enum(['carcass', 'shutter', 'drawer', 'shelf', 'loft', 'dummy_filler', 'profile_glass', 'back_panel', 'countertop', 'plinth_skirting', 'lighting_anchor', 'service_void', 'hardware', 'cnc_panel', 'appliance_void']);
export const ModuleProductionRoleSchema = z.enum(['visual', 'assembly', 'cutlist', 'service', 'accessory']);
export const ModuleElementSchema = z.object({
  kind: ModuleElementKindSchema,
  label: z.string().min(1),
  quantity: z.number().int().positive().default(1),
  widthMm: z.number().positive().optional(),
  depthMm: z.number().positive().optional(),
  heightMm: z.number().positive().optional(),
  materialSlot: MaterialSlotSchema.optional(),
  productionRole: ModuleProductionRoleSchema.default('assembly'),
  notes: z.array(z.string()).default([]),
});
export type ModuleElement = z.infer<typeof ModuleElementSchema>;

export const ModuleConstraintSchema = z.object({
  kind: z.enum(['wall_anchored', 'opening_clearance', 'service_clearance', 'circulation', 'adjacency', 'stacking']),
  label: z.string().min(1),
  valueMm: z.number().nonnegative().optional(),
  required: z.boolean().default(true),
});
export type ModuleConstraint = z.infer<typeof ModuleConstraintSchema>;

export const CatalogModuleSchema = z.object({
  id: z.string(), family: ModuleFamilySchema, name: z.string(), roomTypes: z.array(RoomTypeSchema).min(1),
  widthMm: z.number().positive(), depthMm: z.number().positive(), heightMm: z.number().positive(),
  minClearanceMm: z.number().nonnegative(), sku: z.string(), materialSlots: z.array(MaterialSlotSchema),
  tags: z.array(z.string()), production: z.object({ panelBased: z.boolean(), hardwareSchedule: z.boolean(), cutlistSupported: z.boolean() })
  ,description: z.string().optional(), manufacturingRules: z.array(z.string()).optional(),
  elements: z.array(ModuleElementSchema).optional(), constraints: z.array(ModuleConstraintSchema).optional()
});
export type CatalogModule = z.infer<typeof CatalogModuleSchema>;

// Curated starting palette: intentionally small, brand-labelled, and never
// treated as a substitute for a supplier's current technical datasheet.
export const CuratedLaminateCatalog = [
  { id: 'cubex-neutral-sand', brand: 'Cubex', name: 'Neutral Sand', family: 'solid', finish: 'matte', thicknessMm: 0.8, edgeBand: { thicknessMm: 1, material: 'PVC', status: 'required' }, suitableFor: ['wardrobe', 'tv-unit', 'crockery', 'bed'] },
  { id: 'cubex-walnut-grain', brand: 'Cubex', name: 'Walnut Grain', family: 'woodgrain', finish: 'textured', thicknessMm: 1, edgeBand: { thicknessMm: 2, material: 'ABS', status: 'required' }, suitableFor: ['tv-unit', 'crockery', 'bed'] },
  { id: 'advance-ivory-matte', brand: 'Advance', name: 'Ivory Matte', family: 'solid', finish: 'matte', thicknessMm: 0.8, edgeBand: { thicknessMm: 1, material: 'PVC', status: 'required' }, suitableFor: ['kitchen', 'wardrobe', 'pooja'] },
  { id: 'advance-stone-grey', brand: 'Advance', name: 'Stone Grey', family: 'stone', finish: 'textured', thicknessMm: 1, edgeBand: { thicknessMm: 2, material: 'PVC', status: 'required' }, suitableFor: ['kitchen', 'tv-unit', 'crockery'] },
  { id: 'virgo-sage-green', brand: 'Virgo', name: 'Sage Green', family: 'solid', finish: 'satin', thicknessMm: 0.8, edgeBand: { thicknessMm: 1, material: 'PVC', status: 'required' }, suitableFor: ['kitchen', 'wardrobe', 'bed'] },
  { id: 'virgo-smoked-oak', brand: 'Virgo', name: 'Smoked Oak', family: 'woodgrain', finish: 'satin', thicknessMm: 1, edgeBand: { thicknessMm: 2, material: 'ABS', status: 'required' }, suitableFor: ['tv-unit', 'bed', 'crockery'] },
] as const;

export const IndianModularDesignPresetSchema = z.object({
  id: z.string(), name: z.string(), family: ModuleFamilySchema, roomTypes: z.array(RoomTypeSchema).min(1),
  referenceStyle: z.array(z.string()), elevationViews: z.array(z.enum(['external', 'internal', 'top', 'section'])).min(1),
  renderRules: z.array(z.string()), productionRules: z.array(z.string())
});
export type IndianModularDesignPreset = z.infer<typeof IndianModularDesignPresetSchema>;

export const IndianModularDesignPresets: IndianModularDesignPreset[] = [
  { id: 'preset-tv-profile-glass', name: 'Floating TV wall with profile-glass display', family: 'tv-unit', roomTypes: ['living'], referenceStyle: ['warm wood', 'off-white shutters', 'profile glass', 'vertical LED'], elevationViews: ['external', 'internal'], renderRules: ['Preserve TV wall proportions', 'Use warm 3000K profile lighting only in the display cabinet', 'Keep a visible ceiling gap unless loft is specified'], productionRules: ['Include glass aluminium profile shutter', 'Include cable-management back panel', 'Generate floating-base clearance'] },
  { id: 'preset-kitchen-l-shape', name: 'L-shaped modular kitchen with lofts', family: 'kitchen-base', roomTypes: ['kitchen'], referenceStyle: ['matte laminate', '20mm granite', 'dado tiles', 'under-cabinet light'], elevationViews: ['external', 'internal', 'top'], renderRules: ['Preserve appliance and service locations', 'Use 20mm countertop', 'Do not invent lighting outside specified zones'], productionRules: ['Separate base, wall, tall and blind-corner units', 'Schedule granite and edge bands', 'Record sink, hob and appliance cutouts'] },
  { id: 'preset-wardrobe-equal-shutters', name: 'Equal-shutter wardrobe with loft and profile bay', family: 'wardrobe', roomTypes: ['bedroom'], referenceStyle: ['equal shutters', 'loft', 'long handles', 'profile-glass bay'], elevationViews: ['external', 'internal'], renderRules: ['Use 560mm carcass plus 20mm back as 580mm total depth', 'Keep shutter widths equal unless explicitly overridden'], productionRules: ['Use 18mm panels', 'Include 30mm dummy or filler where specified', 'Separate hanger, shelf and drawer parts'] },
  { id: 'preset-study-whiteboard', name: 'Study desk with marker-safe back panel', family: 'study', roomTypes: ['study', 'bedroom'], referenceStyle: ['floating desk', 'open shelf', 'marker-safe whiteboard laminate'], elevationViews: ['external', 'internal'], renderRules: ['Remove drawers when requested', 'Keep task lighting directional and restrained'], productionRules: ['Mark whiteboard laminate as a dedicated back-panel material', 'Generate desk, shelf and support parts'] },
  { id: 'preset-pooja-tray-jaali', name: 'Pooja unit with tray, fluted glass and jaali', family: 'pooja', roomTypes: ['pooja', 'living'], referenceStyle: ['fluted glass', 'jaali', 'bells', 'warm concealed lighting'], elevationViews: ['external', 'internal', 'section'], renderRules: ['Keep two drawers below the pooja tray', 'Use a single main tray', 'Keep bells and jaali as explicit accessories'], productionRules: ['Separate tray, drawers, shutters and CNC jaali panel', 'Validate cutout vector before release'] }
];

export function listDesignPresets(roomType?: z.infer<typeof RoomTypeSchema>, family?: z.infer<typeof ModuleFamilySchema>) {
  return IndianModularDesignPresets.filter((preset) => (!roomType || preset.roomTypes.includes(roomType)) && (!family || preset.family === family));
}

export const IndianModularCatalog: CatalogModule[] = [
  { id: 'kit-base-600', family: 'kitchen-base', name: '600 base cabinet', roomTypes: ['kitchen'], widthMm: 600, depthMm: 600, heightMm: 750, minClearanceMm: 900, sku: 'ULT-KB-600', materialSlots: ['carcass', 'shutter', 'hardware', 'countertop'], tags: ['modular-kitchen', 'drawer', 'shutter'], production: { panelBased: true, hardwareSchedule: true, cutlistSupported: true } },
  { id: 'kit-wall-600', family: 'kitchen-wall', name: '600 wall cabinet with loft option', roomTypes: ['kitchen', 'utility'], widthMm: 600, depthMm: 350, heightMm: 720, minClearanceMm: 900, sku: 'ULT-KW-600', materialSlots: ['carcass', 'shutter', 'hardware', 'lighting'], tags: ['modular-kitchen', 'wall-unit', 'loft', 'shutter'], production: { panelBased: true, hardwareSchedule: true, cutlistSupported: true }, description: 'Upper storage module for equal shutters, glass shutters, or open shelf compositions.', manufacturingRules: ['Use 18mm carcass panels', 'Keep task-light clearance below wall units'] },
  { id: 'kit-corner-900', family: 'kitchen-corner', name: '900 blind-corner base unit', roomTypes: ['kitchen'], widthMm: 900, depthMm: 600, heightMm: 750, minClearanceMm: 1050, sku: 'ULT-KC-900', materialSlots: ['carcass', 'shutter', 'hardware', 'countertop'], tags: ['modular-kitchen', 'blind-corner', 'l-shaped'], production: { panelBased: true, hardwareSchedule: true, cutlistSupported: true }, description: 'Corner base for L and U kitchens with serviceable access and filler control.', manufacturingRules: ['Reserve corner filler before placement', 'Validate door swing and adjacent appliance clearance'] },
  { id: 'kit-sink-900', family: 'kitchen-base', name: '900 sink base', roomTypes: ['kitchen', 'utility'], widthMm: 900, depthMm: 600, heightMm: 750, minClearanceMm: 900, sku: 'ULT-KS-900', materialSlots: ['carcass', 'shutter', 'hardware', 'countertop'], tags: ['sink', 'plumbing', 'modular-kitchen'], production: { panelBased: true, hardwareSchedule: true, cutlistSupported: true } },
  { id: 'kit-tall-600', family: 'kitchen-tall', name: '600 appliance tall unit', roomTypes: ['kitchen'], widthMm: 600, depthMm: 600, heightMm: 2100, minClearanceMm: 900, sku: 'ULT-KT-600', materialSlots: ['carcass', 'shutter', 'hardware'], tags: ['oven', 'microwave', 'tall-unit'], production: { panelBased: true, hardwareSchedule: true, cutlistSupported: true } },
  { id: 'kit-drawer-900', family: 'kitchen-base', name: '900 three-drawer base', roomTypes: ['kitchen', 'utility'], widthMm: 900, depthMm: 600, heightMm: 750, minClearanceMm: 900, sku: 'ULT-KB-DR-900', materialSlots: ['carcass', 'shutter', 'hardware', 'countertop'], tags: ['modular-kitchen', 'tandem', 'three-drawer'], production: { panelBased: true, hardwareSchedule: true, cutlistSupported: true }, description: 'Wide three-drawer base for cutlery, utensils, and deep storage.' },
  { id: 'kit-glass-wall-900', family: 'kitchen-wall', name: '900 profile-glass wall cabinet', roomTypes: ['kitchen', 'dining'], widthMm: 900, depthMm: 350, heightMm: 720, minClearanceMm: 900, sku: 'ULT-KW-GL-900', materialSlots: ['carcass', 'glass', 'hardware', 'lighting'], tags: ['kitchen', 'profile-glass', 'display', 'wall-unit'], production: { panelBased: true, hardwareSchedule: true, cutlistSupported: true }, description: 'A shallow upper display cabinet with balanced glass shutters and optional internal lighting.' },
  { id: 'kit-pantry-900', family: 'kitchen-tall', name: '900 pantry tall unit', roomTypes: ['kitchen', 'utility'], widthMm: 900, depthMm: 600, heightMm: 2400, minClearanceMm: 900, sku: 'ULT-KT-PN-900', materialSlots: ['carcass', 'shutter', 'hardware'], tags: ['kitchen', 'pantry', 'tall-unit', 'loft'], production: { panelBased: true, hardwareSchedule: true, cutlistSupported: true }, description: 'Full-height pantry storage with equal shutters and a dedicated loft zone.' },
  { id: 'wardrobe-900', family: 'wardrobe', name: '900 sliding wardrobe bay', roomTypes: ['bedroom'], widthMm: 900, depthMm: 600, heightMm: 2400, minClearanceMm: 900, sku: 'ULT-WD-900', materialSlots: ['carcass', 'shutter', 'hardware', 'glass'], tags: ['sliding', 'loft', 'modular-storage'], production: { panelBased: true, hardwareSchedule: true, cutlistSupported: true } },
  { id: 'wardrobe-2100-four-shutter', family: 'wardrobe', name: '2100 four-shutter wardrobe with loft', roomTypes: ['bedroom'], widthMm: 2100, depthMm: 600, heightMm: 2700, minClearanceMm: 900, sku: 'ULT-WD-4S-2100', materialSlots: ['carcass', 'shutter', 'hardware'], tags: ['wardrobe', 'four-shutter', 'loft', 'long-handles'], production: { panelBased: true, hardwareSchedule: true, cutlistSupported: true }, description: 'Master-bedroom four-shutter wardrobe with a separate full-width loft and paired handles.' },
  { id: 'wardrobe-1800-profile-bay', family: 'wardrobe', name: '1800 wardrobe with profile-glass bay', roomTypes: ['bedroom'], widthMm: 1800, depthMm: 600, heightMm: 2700, minClearanceMm: 900, sku: 'ULT-WD-PG-1800', materialSlots: ['carcass', 'shutter', 'glass', 'hardware', 'lighting'], tags: ['wardrobe', 'profile-glass', 'loft', 'display'], production: { panelBased: true, hardwareSchedule: true, cutlistSupported: true }, description: 'Full-height wardrobe with one controlled profile-glass display bay and closed lofts.' },
  { id: 'tv-1800', family: 'tv-unit', name: '1800 TV console', roomTypes: ['living', 'bedroom'], widthMm: 1800, depthMm: 400, heightMm: 600, minClearanceMm: 900, sku: 'ULT-TV-1800', materialSlots: ['carcass', 'shutter', 'back-panel', 'hardware'], tags: ['tv-wall', 'console', 'cable-management'], production: { panelBased: true, hardwareSchedule: true, cutlistSupported: true } },
  { id: 'tv-profile-2400', family: 'tv-unit', name: '2400 TV wall with profile glass', roomTypes: ['living'], widthMm: 2400, depthMm: 400, heightMm: 2400, minClearanceMm: 900, sku: 'ULT-TV-PROFILE-2400', materialSlots: ['carcass', 'shutter', 'back-panel', 'glass', 'hardware', 'lighting'], tags: ['tv-wall', 'profile-glass', 'floating-base', 'lighting'], production: { panelBased: true, hardwareSchedule: true, cutlistSupported: true } },
  { id: 'tv-floating-1600', family: 'tv-unit', name: '1600 floating TV console', roomTypes: ['living', 'bedroom'], widthMm: 1600, depthMm: 400, heightMm: 550, minClearanceMm: 900, sku: 'ULT-TV-FLOAT-1600', materialSlots: ['carcass', 'shutter', 'back-panel', 'hardware', 'lighting'], tags: ['tv-wall', 'floating', 'minimal', 'gola'], production: { panelBased: true, hardwareSchedule: true, cutlistSupported: true }, description: 'Minimal floating console with cable back panel and optional under-base LED.', manufacturingRules: ['Maintain 200mm approved floating clearance', 'Keep lighting only at configured anchors'] },
  { id: 'tv-fluted-2100', family: 'tv-unit', name: '2100 fluted-panel TV wall', roomTypes: ['living'], widthMm: 2100, depthMm: 400, heightMm: 2300, minClearanceMm: 900, sku: 'ULT-TV-FLUTE-2100', materialSlots: ['carcass', 'shutter', 'back-panel', 'hardware', 'lighting'], tags: ['tv-wall', 'fluted-panel', 'floating-base', 'warm-light'], production: { panelBased: true, hardwareSchedule: true, cutlistSupported: true }, description: 'Feature TV panel with a fluted zone, floating base, and restrained warm lighting.' },
  { id: 'tv-asymmetric-2400', family: 'tv-unit', name: '2400 asymmetric TV and display wall', roomTypes: ['living'], widthMm: 2400, depthMm: 400, heightMm: 2400, minClearanceMm: 900, sku: 'ULT-TV-ASYM-2400', materialSlots: ['carcass', 'shutter', 'back-panel', 'glass', 'hardware', 'lighting'], tags: ['tv-wall', 'asymmetric', 'display', 'profile-glass'], production: { panelBased: true, hardwareSchedule: true, cutlistSupported: true }, description: 'TV composition with one profile-glass display tower and balanced lower storage.' },
  { id: 'tv-study-2700', family: 'tv-unit', name: '2700 TV plus study wall', roomTypes: ['living', 'study'], widthMm: 2700, depthMm: 600, heightMm: 2400, minClearanceMm: 900, sku: 'ULT-TV-STUDY-2700', materialSlots: ['carcass', 'shutter', 'back-panel', 'hardware', 'lighting'], tags: ['tv-wall', 'study', 'desk', 'storage'], production: { panelBased: true, hardwareSchedule: true, cutlistSupported: true }, description: 'Combined TV wall and desk with configurable drawer-free study bay.' },
  { id: 'tv-crockery-3000', family: 'tv-unit', name: '3000 TV plus crockery wall', roomTypes: ['living', 'dining'], widthMm: 3000, depthMm: 450, heightMm: 2400, minClearanceMm: 900, sku: 'ULT-TV-CR-3000', materialSlots: ['carcass', 'shutter', 'back-panel', 'glass', 'hardware', 'lighting'], tags: ['tv-wall', 'crockery', 'profile-glass', 'dining'], production: { panelBased: true, hardwareSchedule: true, cutlistSupported: true }, description: 'Living-to-dining composition with TV centre, display glazing, and lower storage.' },
  { id: 'tv-partition-2400', family: 'tv-unit', name: '2400 partition TV unit', roomTypes: ['living'], widthMm: 2400, depthMm: 450, heightMm: 2400, minClearanceMm: 1000, sku: 'ULT-TV-PART-2400', materialSlots: ['carcass', 'shutter', 'back-panel', 'metal', 'hardware', 'lighting'], tags: ['tv-wall', 'partition', 'slatted', 'open-plan'], production: { panelBased: true, hardwareSchedule: true, cutlistSupported: true }, description: 'Open-plan partition with a TV back, slatted screen, and accessible service cavity.' },
  { id: 'tv-full-wall-3200', family: 'tv-unit', name: '3200 full-wall TV storage', roomTypes: ['living'], widthMm: 3200, depthMm: 450, heightMm: 2400, minClearanceMm: 900, sku: 'ULT-TV-FULL-3200', materialSlots: ['carcass', 'shutter', 'back-panel', 'glass', 'hardware', 'lighting'], tags: ['tv-wall', 'full-wall', 'loft', 'storage'], production: { panelBased: true, hardwareSchedule: true, cutlistSupported: true }, description: 'Full-width storage composition with a central TV field, closed lofts, and side display bays.' },
  { id: 'tv-classic-2200', family: 'tv-unit', name: '2200 modern-classic TV wall', roomTypes: ['living', 'bedroom'], widthMm: 2200, depthMm: 400, heightMm: 2200, minClearanceMm: 900, sku: 'ULT-TV-CLASSIC-2200', materialSlots: ['carcass', 'shutter', 'back-panel', 'metal', 'hardware', 'lighting'], tags: ['tv-wall', 'modern-classic', 'panelling', 'brass'], production: { panelBased: true, hardwareSchedule: true, cutlistSupported: true }, description: 'Panelled TV wall with a symmetric back panel, slim metal accents, and enclosed base storage.' },
  { id: 'tv-arch-3000', family: 'tv-unit', name: '3000 arched niche TV and crockery wall', roomTypes: ['living', 'dining'], widthMm: 3000, depthMm: 450, heightMm: 2550, minClearanceMm: 950, sku: 'ULT-TV-ARCH-3000', materialSlots: ['carcass', 'shutter', 'back-panel', 'glass', 'hardware', 'lighting'], tags: ['tv-wall', 'arched-niche', 'crockery', 'profile-glass', 'warm-light'], production: { panelBased: true, hardwareSchedule: true, cutlistSupported: true }, description: 'A measured TV field framed by display bays, panel detailing, and a controlled illuminated arch/niche treatment.', manufacturingRules: ['Model arch as an approved elevation detail; do not infer radius from reference imagery', 'Maintain explicit display-bay glass widths and cable service access'] },
  { id: 'tv-slat-2800', family: 'tv-unit', name: '2800 slatted partition TV wall', roomTypes: ['living'], widthMm: 2800, depthMm: 450, heightMm: 2400, minClearanceMm: 1000, sku: 'ULT-TV-SLAT-2800', materialSlots: ['carcass', 'shutter', 'back-panel', 'hardware', 'lighting'], tags: ['tv-wall', 'slatted', 'partition', 'open-plan', 'floating-base'], production: { panelBased: true, hardwareSchedule: true, cutlistSupported: true }, description: 'TV storage with a transparent slatted edge screen, floating console, and serviceable wire cavity.', manufacturingRules: ['Keep partition slat spacing and end clearances explicit', 'Do not use the screen as a structural wall'] },
  { id: 'tv-study-3400', family: 'tv-unit', name: '3400 TV library and study wall', roomTypes: ['living', 'study'], widthMm: 3400, depthMm: 600, heightMm: 2400, minClearanceMm: 1000, sku: 'ULT-TV-LIB-3400', materialSlots: ['carcass', 'shutter', 'back-panel', 'hardware', 'lighting'], tags: ['tv-wall', 'study', 'library', 'worktop', 'drawers'], production: { panelBased: true, hardwareSchedule: true, cutlistSupported: true }, description: 'TV wall with a full-depth worktop, drawer pedestal, upper storage, and controlled task-light anchor.', manufacturingRules: ['Reserve chair circulation in the approved layout', 'Keep study worktop depth at or below the verified available room clearance'] },
  { id: 'crockery-1200', family: 'crockery', name: '1200 crockery display unit', roomTypes: ['living', 'dining'], widthMm: 1200, depthMm: 400, heightMm: 2100, minClearanceMm: 900, sku: 'ULT-CR-1200', materialSlots: ['carcass', 'shutter', 'glass', 'hardware', 'lighting'], tags: ['crockery', 'display', 'profile-glass', 'linear'], production: { panelBased: true, hardwareSchedule: true, cutlistSupported: true }, description: 'Balanced base storage with an illuminated profile-glass display tower.', manufacturingRules: ['Keep glass shutter widths at or below 450mm', 'Use 18mm carcass panels and a serviceable lighting channel'] },
  { id: 'crockery-1800', family: 'crockery', name: '1800 full-wall crockery and bar', roomTypes: ['living', 'dining'], widthMm: 1800, depthMm: 450, heightMm: 2400, minClearanceMm: 900, sku: 'ULT-CR-1800', materialSlots: ['carcass', 'shutter', 'glass', 'hardware', 'lighting', 'countertop'], tags: ['crockery', 'full-wall', 'bar', 'fluted-glass', 'warm-light'], production: { panelBased: true, hardwareSchedule: true, cutlistSupported: true }, description: 'Full-height dining wall with closed overhead storage, display glass, counter niche, and lower drawers.', manufacturingRules: ['Reserve a 200mm counter/service zone where appliances are specified', 'Split glass fronts into balanced bays', 'Coordinate countertop thickness with the project material assignment'] },
  { id: 'crockery-2400', family: 'crockery', name: '2400 crockery with open niches', roomTypes: ['living', 'dining'], widthMm: 2400, depthMm: 450, heightMm: 2400, minClearanceMm: 900, sku: 'ULT-CR-2400', materialSlots: ['carcass', 'shutter', 'glass', 'hardware', 'lighting', 'back-panel'], tags: ['crockery', 'open-niche', 'asymmetric', 'profile-glass', 'fluted-panel'], production: { panelBased: true, hardwareSchedule: true, cutlistSupported: true }, description: 'Asymmetric crockery composition with open display niches, tall profile-glass bays, and a feature back panel.', manufacturingRules: ['Keep open niches aligned to approved wall elevations', 'Use explicit dummy fillers at wall returns', 'Do not add lighting outside assigned shelf/light anchors'] },
  { id: 'crockery-sideboard-1600', family: 'crockery', name: '1600 dining sideboard and display', roomTypes: ['dining', 'living'], widthMm: 1600, depthMm: 450, heightMm: 2100, minClearanceMm: 900, sku: 'ULT-CR-SIDE-1600', materialSlots: ['carcass', 'shutter', 'glass', 'hardware', 'lighting', 'countertop'], tags: ['crockery', 'sideboard', 'display', 'fluted-glass'], production: { panelBased: true, hardwareSchedule: true, cutlistSupported: true }, description: 'Dining sideboard with a counter niche, upper fluted-glass shutters, and closed base storage.' },
  { id: 'crockery-curved-2100', family: 'crockery', name: '2100 curved-corner crockery bar', roomTypes: ['dining', 'living'], widthMm: 2100, depthMm: 450, heightMm: 2400, minClearanceMm: 900, sku: 'ULT-CR-CURVE-2100', materialSlots: ['carcass', 'shutter', 'glass', 'hardware', 'lighting', 'countertop'], tags: ['crockery', 'bar', 'curved-corner', 'profile-glass'], production: { panelBased: true, hardwareSchedule: true, cutlistSupported: true }, description: 'Crockery and bar composition with a curved return, lit display cabinets, and serviceable lower storage.' },
  { id: 'study-1500', family: 'study', name: '1500 study desk with overhead storage', roomTypes: ['study', 'bedroom'], widthMm: 1500, depthMm: 600, heightMm: 2400, minClearanceMm: 900, sku: 'ULT-ST-1500', materialSlots: ['carcass', 'shutter', 'back-panel', 'hardware', 'lighting'], tags: ['study', 'desk', 'overhead-storage'], production: { panelBased: true, hardwareSchedule: true, cutlistSupported: true } },
  { id: 'study-1200', family: 'study', name: '1200 compact study wall', roomTypes: ['study', 'bedroom'], widthMm: 1200, depthMm: 300, heightMm: 2100, minClearanceMm: 750, sku: 'ULT-ST-1200', materialSlots: ['carcass', 'shutter', 'back-panel', 'hardware', 'lighting'], tags: ['study', 'desk', 'open-shelf', 'whiteboard'], production: { panelBased: true, hardwareSchedule: true, cutlistSupported: true }, description: 'Compact desk, drawer-free option, and overhead shelf for smaller rooms.', manufacturingRules: ['Back panel can use marker-safe laminate', 'Keep desk depth and chair clearance explicit'] },
  { id: 'study-library-1800', family: 'study', name: '1800 study and library wall', roomTypes: ['study', 'bedroom'], widthMm: 1800, depthMm: 600, heightMm: 2400, minClearanceMm: 900, sku: 'ULT-ST-LB-1800', materialSlots: ['carcass', 'shutter', 'back-panel', 'hardware', 'lighting'], tags: ['study', 'library', 'desk', 'open-shelf'], production: { panelBased: true, hardwareSchedule: true, cutlistSupported: true }, description: 'Desk with tall open-library bay, closed upper storage, and a configurable drawer-free worktop.' },
  { id: 'pooja-900', family: 'pooja', name: '900 pooja unit with tray', roomTypes: ['pooja', 'living'], widthMm: 900, depthMm: 400, heightMm: 1800, minClearanceMm: 750, sku: 'ULT-PJ-900', materialSlots: ['carcass', 'shutter', 'back-panel', 'hardware', 'lighting'], tags: ['pooja', 'pull-out-tray', 'jaali'], production: { panelBased: true, hardwareSchedule: true, cutlistSupported: true } },
  { id: 'pooja-1200-jaali', family: 'pooja', name: '1200 pooja wall with jaali shutters', roomTypes: ['pooja', 'living'], widthMm: 1200, depthMm: 400, heightMm: 2100, minClearanceMm: 750, sku: 'ULT-PJ-JL-1200', materialSlots: ['carcass', 'shutter', 'back-panel', 'hardware', 'lighting'], tags: ['pooja', 'jaali', 'fluted-glass', 'tray'], production: { panelBased: true, hardwareSchedule: true, cutlistSupported: true }, description: 'A full-height pooja composition with one main tray, lower storage, and a CNC jaali zone.' },
  { id: 'utility-900', family: 'utility', name: '900 utility storage tower', roomTypes: ['utility', 'kitchen'], widthMm: 900, depthMm: 600, heightMm: 2100, minClearanceMm: 900, sku: 'ULT-UT-900', materialSlots: ['carcass', 'shutter', 'hardware'], tags: ['utility', 'laundry', 'storage'], production: { panelBased: true, hardwareSchedule: true, cutlistSupported: true } },
  { id: 'utility-laundry-1500', family: 'utility', name: '1500 laundry and utility wall', roomTypes: ['utility'], widthMm: 1500, depthMm: 650, heightMm: 2400, minClearanceMm: 1000, sku: 'ULT-UT-LN-1500', materialSlots: ['carcass', 'shutter', 'countertop', 'hardware'], tags: ['utility', 'laundry', 'washing-machine', 'tall-storage'], production: { panelBased: true, hardwareSchedule: true, cutlistSupported: true }, description: 'A service-aware utility wall with washer void, counter, tall storage, and closed lofts.' },
  { id: 'storage-shoe-1200', family: 'storage', name: '1200 entry shoe and storage unit', roomTypes: ['living', 'other'], widthMm: 1200, depthMm: 400, heightMm: 2100, minClearanceMm: 900, sku: 'ULT-SR-SH-1200', materialSlots: ['carcass', 'shutter', 'hardware', 'lighting'], tags: ['storage', 'shoe', 'foyer', 'open-shelf'], production: { panelBased: true, hardwareSchedule: true, cutlistSupported: true }, description: 'Entry storage with ventilated shoe shutters, a small seat niche, and closed top storage.' },
  { id: 'ceiling-l-3000', family: 'false-ceiling', name: '3000 L-shaped peripheral false ceiling', roomTypes: ['bedroom', 'living', 'study'], widthMm: 3000, depthMm: 2400, heightMm: 120, minClearanceMm: 2100, sku: 'ULT-FC-L-3000', materialSlots: ['lighting', 'back-panel'], tags: ['false-ceiling', 'l-shaped', 'peripheral', 'spotlights'], production: { panelBased: false, hardwareSchedule: true, cutlistSupported: false }, description: 'A measured L-shaped peripheral ceiling with a restrained inner strip-light anchor and spot-light positions.' },
  { id: 'bed-1800', family: 'bed', name: '1800 hydraulic storage bed', roomTypes: ['bedroom'], widthMm: 1800, depthMm: 2100, heightMm: 450, minClearanceMm: 750, sku: 'ULT-BD-1800', materialSlots: ['carcass', 'shutter', 'hardware', 'fabric'], tags: ['bedroom', 'storage-bed', 'hydraulic'], production: { panelBased: true, hardwareSchedule: true, cutlistSupported: true } },
  { id: 'bed-1500-headboard', family: 'bed', name: '1500 queen bed with headboard wall', roomTypes: ['bedroom'], widthMm: 1500, depthMm: 2100, heightMm: 1100, minClearanceMm: 750, sku: 'ULT-BD-HB-1500', materialSlots: ['carcass', 'fabric', 'back-panel', 'lighting'], tags: ['bedroom', 'queen-bed', 'headboard', 'storage'], production: { panelBased: true, hardwareSchedule: true, cutlistSupported: true }, description: 'Queen storage bed with a panelled headboard and controlled reading-light anchors.' },
  { id: 'dining-1600', family: 'dining', name: '1600 six-seat dining set', roomTypes: ['dining', 'living'], widthMm: 1600, depthMm: 900, heightMm: 750, minClearanceMm: 900, sku: 'ULT-DN-1600', materialSlots: ['metal', 'fabric'], tags: ['dining', 'six-seat', 'furniture'], production: { panelBased: false, hardwareSchedule: false, cutlistSupported: false } },
  { id: 'dining-1800-eight-seat', family: 'dining', name: '1800 eight-seat dining set', roomTypes: ['dining', 'living'], widthMm: 1800, depthMm: 1000, heightMm: 750, minClearanceMm: 1000, sku: 'ULT-DN-1800', materialSlots: ['metal', 'fabric'], tags: ['dining', 'eight-seat', 'furniture'], production: { panelBased: false, hardwareSchedule: false, cutlistSupported: false }, description: 'Eight-seat dining set with generous circulation for a formal dining room.' },
  { id: 'sofa-2200', family: 'sofa', name: '2200 three-seat sofa', roomTypes: ['living'], widthMm: 2200, depthMm: 900, heightMm: 850, minClearanceMm: 750, sku: 'ULT-SF-2200', materialSlots: ['fabric', 'metal'], tags: ['living', 'three-seat', 'standard-size'], production: { panelBased: false, hardwareSchedule: false, cutlistSupported: false } },
  { id: 'sofa-l-2800', family: 'sofa', name: '2800 L-shaped sectional sofa', roomTypes: ['living'], widthMm: 2800, depthMm: 1700, heightMm: 850, minClearanceMm: 900, sku: 'ULT-SF-L-2800', materialSlots: ['fabric', 'metal'], tags: ['living', 'sectional', 'l-shaped', 'chaise'], production: { panelBased: false, hardwareSchedule: false, cutlistSupported: false }, description: 'L-shaped sectional with a right or left chaise chosen only after room verification.' }
];

export function listCatalog(roomType?: z.infer<typeof RoomTypeSchema>, query?: string) {
  const normalized = query?.trim().toLowerCase();
  return IndianModularCatalog.filter((item) => (!roomType || item.roomTypes.includes(roomType)) && (!normalized || `${item.name} ${item.tags.join(' ')}`.toLowerCase().includes(normalized)));
}

const FAMILY_ELEMENTS: Record<z.infer<typeof ModuleFamilySchema>, z.input<typeof ModuleElementSchema>[]> = {
  'kitchen-base': [
    { kind: 'carcass', label: '18mm base carcass', materialSlot: 'carcass', productionRole: 'assembly', notes: ['Include serviceable back clearance.'] },
    { kind: 'shutter', label: 'Base shutters', materialSlot: 'shutter', productionRole: 'cutlist', notes: ['Keep reveal consistent.'] },
    { kind: 'drawer', label: 'Configured drawers', materialSlot: 'shutter', productionRole: 'cutlist', notes: [] },
    { kind: 'plinth_skirting', label: '110mm plinth/skirting', materialSlot: 'carcass', productionRole: 'cutlist', notes: [] },
    { kind: 'countertop', label: 'Countertop slab', materialSlot: 'countertop', productionRole: 'cutlist', notes: ['Thickness must come from project requirements, never a visual estimate.'] },
    { kind: 'service_void', label: 'Plumbing and appliance service void', productionRole: 'service', notes: ['Verify on site before fabrication.'] },
  ],
  'kitchen-wall': [
    { kind: 'carcass', label: '18mm wall carcass', materialSlot: 'carcass', productionRole: 'assembly', notes: [] },
    { kind: 'shutter', label: 'Wall shutters', materialSlot: 'shutter', productionRole: 'cutlist', notes: [] },
    { kind: 'shelf', label: 'Adjustable shelves', materialSlot: 'carcass', productionRole: 'cutlist', notes: [] },
    { kind: 'lighting_anchor', label: 'Under-cabinet light anchor', materialSlot: 'lighting', productionRole: 'accessory', notes: ['Only where specified.'] },
  ],
  'kitchen-tall': [{ kind: 'carcass', label: 'Tall carcass', materialSlot: 'carcass', productionRole: 'assembly', notes: [] }, { kind: 'shutter', label: 'Tall shutters', materialSlot: 'shutter', productionRole: 'cutlist', notes: [] }, { kind: 'appliance_void', label: 'Appliance void', productionRole: 'service', notes: ['Use approved appliance dimensions.'] }],
  'kitchen-corner': [{ kind: 'carcass', label: 'Corner carcass', materialSlot: 'carcass', productionRole: 'assembly', notes: ['Reserve filler before adjacent shutters.'] }, { kind: 'shutter', label: 'Corner shutter', materialSlot: 'shutter', productionRole: 'cutlist', notes: [] }, { kind: 'dummy_filler', label: 'Corner filler', materialSlot: 'carcass', productionRole: 'cutlist', notes: ['Required to prevent handle collision.'] }],
  wardrobe: [{ kind: 'carcass', label: '18mm wardrobe carcass', materialSlot: 'carcass', productionRole: 'assembly', notes: ['Typical depth is 560mm carcass plus 20mm back when approved.'] }, { kind: 'shutter', label: 'Equal wardrobe shutters', materialSlot: 'shutter', productionRole: 'cutlist', notes: [] }, { kind: 'loft', label: 'Loft shutters', materialSlot: 'shutter', productionRole: 'cutlist', notes: [] }, { kind: 'shelf', label: 'Adjustable shelves', materialSlot: 'carcass', productionRole: 'cutlist', notes: [] }, { kind: 'drawer', label: 'Drawer stack', materialSlot: 'shutter', productionRole: 'cutlist', notes: [] }, { kind: 'dummy_filler', label: 'Dummy/filler', materialSlot: 'carcass', productionRole: 'cutlist', notes: ['Use only where the approved design specifies it.'] }, { kind: 'hardware', label: 'Handles and sliding hardware', materialSlot: 'hardware', productionRole: 'accessory', notes: [] }],
  'tv-unit': [{ kind: 'back_panel', label: 'TV back panel', materialSlot: 'back-panel', productionRole: 'cutlist', notes: ['Preserve exact approved TV and cable positions.'] }, { kind: 'carcass', label: 'Base carcass', materialSlot: 'carcass', productionRole: 'assembly', notes: [] }, { kind: 'shutter', label: 'Base shutters', materialSlot: 'shutter', productionRole: 'cutlist', notes: [] }, { kind: 'profile_glass', label: 'Aluminium profile glass display', materialSlot: 'glass', productionRole: 'cutlist', notes: ['Add internal lighting only when specified.'] }, { kind: 'lighting_anchor', label: 'Display/profile light anchor', materialSlot: 'lighting', productionRole: 'accessory', notes: [] }],
  crockery: [{ kind: 'carcass', label: 'Display carcass', materialSlot: 'carcass', productionRole: 'assembly', notes: [] }, { kind: 'profile_glass', label: 'Glass display shutters', materialSlot: 'glass', productionRole: 'cutlist', notes: [] }, { kind: 'shelf', label: 'Glass shelves', materialSlot: 'glass', productionRole: 'cutlist', notes: [] }, { kind: 'lighting_anchor', label: 'Shelf light anchors', materialSlot: 'lighting', productionRole: 'accessory', notes: [] }],
  study: [{ kind: 'carcass', label: 'Study carcass', materialSlot: 'carcass', productionRole: 'assembly', notes: [] }, { kind: 'back_panel', label: 'Marker-safe back panel', materialSlot: 'back-panel', productionRole: 'cutlist', notes: ['Use a verified whiteboard-compatible finish.'] }, { kind: 'shelf', label: 'Open shelves', materialSlot: 'carcass', productionRole: 'cutlist', notes: [] }, { kind: 'drawer', label: 'Optional drawers', materialSlot: 'shutter', productionRole: 'cutlist', notes: ['Omit when the brief says drawer-free.'] }],
  pooja: [{ kind: 'carcass', label: 'Pooja carcass', materialSlot: 'carcass', productionRole: 'assembly', notes: [] }, { kind: 'drawer', label: 'Two drawers below tray', materialSlot: 'shutter', productionRole: 'cutlist', notes: [] }, { kind: 'shelf', label: 'Single pooja tray', materialSlot: 'carcass', productionRole: 'cutlist', notes: ['Do not split into two trays.'] }, { kind: 'shutter', label: 'Main shutters', materialSlot: 'shutter', productionRole: 'cutlist', notes: [] }, { kind: 'profile_glass', label: 'Fluted glass shutter', materialSlot: 'glass', productionRole: 'cutlist', notes: [] }, { kind: 'cnc_panel', label: 'Jaali/CNC panel', productionRole: 'cutlist', notes: ['Release only after vector preflight.'] }, { kind: 'lighting_anchor', label: 'Concealed warm light anchor', materialSlot: 'lighting', productionRole: 'accessory', notes: [] }],
  utility: [{ kind: 'carcass', label: 'Utility carcass', materialSlot: 'carcass', productionRole: 'assembly', notes: [] }, { kind: 'shutter', label: 'Utility shutters', materialSlot: 'shutter', productionRole: 'cutlist', notes: [] }, { kind: 'service_void', label: 'Plumbing/service void', productionRole: 'service', notes: [] }],
  sofa: [{ kind: 'carcass', label: 'Sofa frame', materialSlot: 'carcass', productionRole: 'assembly', notes: [] }, { kind: 'hardware', label: 'Sofa hardware', materialSlot: 'hardware', productionRole: 'accessory', notes: [] }],
  bed: [{ kind: 'carcass', label: 'Bed platform', materialSlot: 'carcass', productionRole: 'assembly', notes: [] }, { kind: 'hardware', label: 'Hydraulic hardware', materialSlot: 'hardware', productionRole: 'accessory', notes: [] }],
  dining: [{ kind: 'carcass', label: 'Dining frame', productionRole: 'assembly', notes: [] }],
  'false-ceiling': [{ kind: 'lighting_anchor', label: 'False-ceiling light anchor', materialSlot: 'lighting', productionRole: 'accessory', notes: [] }],
  storage: [{ kind: 'carcass', label: 'Storage carcass', materialSlot: 'carcass', productionRole: 'assembly', notes: [] }, { kind: 'shutter', label: 'Storage shutters', materialSlot: 'shutter', productionRole: 'cutlist', notes: [] }, { kind: 'shelf', label: 'Storage shelves', materialSlot: 'carcass', productionRole: 'cutlist', notes: [] }],
};

export function moduleElementsFor(module: CatalogModule): ModuleElement[] {
  return module.elements?.map((element) => ModuleElementSchema.parse(element)) ?? FAMILY_ELEMENTS[module.family].map((element) => ModuleElementSchema.parse(element));
}

export function moduleConstraintsFor(module: CatalogModule): ModuleConstraint[] {
  return module.constraints?.map((constraint) => ModuleConstraintSchema.parse(constraint)) ?? [
    { kind: 'wall_anchored', label: 'Anchor to a valid wall or room placement', required: true },
    { kind: 'circulation', label: `Maintain at least ${module.minClearanceMm}mm clear circulation`, valueMm: module.minClearanceMm, required: true },
  ];
}

export function getCatalogVault() {
  return {
    version: 'modular-vault.v1',
    sourceOfTruth: 'Approved plan, layout, scene.v1, and production contracts; references are advisory.',
    families: ModuleFamilySchema.options.map((family) => ({ family, modules: IndianModularCatalog.filter((module) => module.family === family).map((module) => module.id) })),
    elementKinds: ModuleElementKindSchema.options,
    constraints: ['wall_anchored', 'opening_clearance', 'service_clearance', 'circulation', 'adjacency', 'stacking'],
    modules: IndianModularCatalog.map((module) => ({ ...module, elements: moduleElementsFor(module), constraints: moduleConstraintsFor(module) })),
    presets: IndianModularDesignPresets,
  };
}

export function validatePlacement(module: CatalogModule, roomType: z.infer<typeof RoomTypeSchema>, clearanceMm: number) {
  const issues: string[] = [];
  if (!module.roomTypes.includes(roomType)) issues.push(`${module.name} is not catalogued for ${roomType}.`);
  if (clearanceMm < module.minClearanceMm) issues.push(`${module.name} needs at least ${module.minClearanceMm} mm clear circulation.`);
  return { valid: issues.length === 0, issues };
}
